### ISSUE TITLE
Break time inaccurate 

### ISSUE THREAD

**Issue by Saumya199** [DeviPrasadKL/Logout_legend#3]
We logged in at 9.39.26 am and our log out time showing in the app is 5.41.52pm but ideal it should be approximately 6.40pm including breaks.

Kindly fix it asap,

![screenshot_2024-08-12-17-04-11-129_com android chrome_720](https://github.com/user-attachments/assets/7d11514a-47ab-4f63-923a-c912d81a90e7)

**Comment by DeviPrasadKL** [comment]
Hi Saumya199,

Thank you for bringing this to our attention. We have reviewed and corrected the issue. 

We appreciate your vigilance in helping us maintain accurate records. If you have any more concerns or need further assistance, please feel free to reach out.
